# Generated by Django 4.0.5 on 2022-07-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Otimizar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sobras',
            new_name='Peca',
        ),
        migrations.RenameModel(
            old_name='Pecas',
            new_name='Sobra',
        ),
    ]
