# Generated by Django 4.0.5 on 2022-07-03 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Otimizar', '0002_rename_sobras_peca_rename_pecas_sobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aproveita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Otimizar.peca')),
                ('sobra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Otimizar.sobra')),
            ],
        ),
    ]
